language: cpp

sudo: required

compiler: gcc

services:
  - docker

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        targetFile=DoujinFix
        releaseName=DoujinFix_ubuntu_xenial_x64
      cache:
        bundler: true
        apt: true
        directories:
          - /opt/qt512/
    - os: osx
      osx_image: xcode10.2
      env: 
        targetFile=DoujinFix
        releaseName=DoujinFix_macos10-14_xcode10-2.dmg
      cache:
        bundler: true
        directories:
          - /usr/local/Cellar/qt/5.12.2/

group: deprecated-2019Q1

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install qt; fi 
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y; sudo apt-get update -qq; sudo apt-get install -y libglew-dev libglfw3-dev; sudo apt-get install -y qt512-meta-minimal; fi

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh; fi
    
script:
    - cd src
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt512/bin/qt512-env.sh; qmake ; make ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/qt/5.12.2/bin/qmake ; make ; fi
    - pwd
    - ls
    - cd /bin
    - ls
    - sudo find / -name DoujinFix
    
before_deploy:
    - ls
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then /usr/local/Cellar/qt/5.12.2/bin/macdeployqt bin/${targetFile}.app -qmldir=/usr/local/Cellar/qt/5.12.2/qml -verbose=1 -dmg ; mv bin/${targetFile}.dmg bin/${releaseName} ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mv bin/${targetFile} bin/${releaseName} ; fi
    
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: bin/${releaseName}
  skip_cleanup: true
  on:
    tags: true
    
notifications:
    email: false
