
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: build-{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
  QT_VER: 5.12.3
  MAKE_RUN_TESTS: true
  TARGET_NAME: DoujinFix

  matrix:
  - QT5: C:\Qt\5.12.2\mingw73_64
    MINGW: C:\Qt\Tools\mingw530_32
    use_cmake: "false"
    
# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

# scripts to run before build
before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

# to run your custom scripts instead of automatic MSBuild
build_script:
  - mkdir .\build
  - cd .\build
  - qmake -v
  - qmake ..\src\DoujinFix.pro CONFIG+=release DESTDIR=%cd% 
  - mingw32-make 
  - DoujinFix.exe
