
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: build-{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
  QT_VER: 5.12.3
  MAKE_RUN_TESTS: true
  TARGET_NAME: DoujinFix

  matrix:
    - PLATFORM: msvc2015_64
    
# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.
  allow_failures:
    - platform: x86
      configuration: Debug
    - platform: x64
      configuration: Release

# exclude configuration from the matrix. Works similarly to 'allow_failures' but build not even being started for excluded combination.
  exclude:
    - platform: x86
      configuration: Debug

install:
  - set QTDIR=C:\Qt\5.12.2\mingw73_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin 

build_script:
  - cd src
  - ls
  - qmake -v
  - qmake DoujinFix.pro CONFIG+=release DESTDIR=%cd% 
  - mingw32-make 
  - DoujinFix.exe
