
# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: '{build}'

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# environment variables
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    platform: x64
    qt: 5.12
    releaseName: DoujinFix_qt512_vs2015_x64
    
# this is how to allow failing jobs in the matrix
matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set msvc=msvc2015
  - set vs=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
  - set QTDIR=C:\Qt\%qt%\%msvc%_64
  - set PATH=%PATH%;%QTDIR%\bin;
  - set vcvarsall=%vs%\vcvarsall.bat
  - mkdir .\build
  - cd .\build
  - call "%vcvarsall%" x64
  - qmake
  - nmake

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
  
artifacts:
  - path: make\release
    name: $(releaseName)
    
#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
#deploy:
#    provider: GitHub
#    auth_token:
#      secure: [token]
#    artifact: release
#    draft: false
#    prerelease: false